version: '3.9'

services:
  llama:
    restart: always
    build:
      context: ${BUILD_CONTEXT}
      dockerfile: ${LLAMA_CUDA_DOCKERFILE}
      args:
        - NPROC=8
    ports:
      - "8000:8000"
    volumes:
      - "${LLAMA_MODEL_PATH}:/app/models"
    command: ${LLAMA_ARGS}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
          cpus: "8"

  sd:
    restart: always
    build:
      context: ${BUILD_CONTEXT}
      dockerfile: ${SD_CUDA_DOCKERFILE}
    ports:
      - "8001:8001"
    volumes:
      - "${SD_MODEL_PATH}:/app/models"
    command: ${SD_ARGS}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
          cpus: "8"

  nginx:
    build: 
      context: ./nginx
      args:
        NGINX_SECRET: ${NGINX_SECRET}
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - llama
      - sd
    environment:
      - NGINX_SECRET=${NGINX_SECRET}