version: '3'

services:
  llama:
    build:
      context: ./
      dockerfile: ./llama-cuda/Dockerfile
      args:
        - NPROC=8
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - llama
