version: '3.9'

services:
  llama:
    restart: always
    build:
      context: ${BUILD_CONTEXT}
      dockerfile: ${LLAMA_VK_DOCKERFILE}
      args:
        - NPROC=8
    ports:
      - "8000:8000"
    volumes:
      - "${LLAMA_MODEL_PATH}:/app"
    command: ${LLAMA_ARGS}
    devices:
      - /dev/dri:/dev/dri

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - llama
    environment:
      - NGINX_SECRET=${NGINX_SECRET}