version: '3'

services:
  llama:
    build:
      context: ./
      dockerfile: ./llama-cuda/Dockerfile
      args:
        - NPROC=8
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - "~/projects/models/:/app"
    command: -m "/app/westlake-7b-v2.Q5_K_M.gguf"

  sd:
    build:
      context: ./
      dockerfile: ./sd-cuda/Dockerfile
      args:
        - NPROC=8
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - "~/projects/models//app"
    command: -m "/app/westlake-7b-v2.Q5_K_M.gguf"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - llama
